/**
 * Safe DOCX builder (REC-05 WU-A, D-024).
 *
 * Builds the minimum valid OOXML (WordprocessingML) package for a plain text
 * document using the existing direct `jszip` dependency. The ONLY content
 * input is the canonical Safe string: this module has no parameter, field or
 * code path that could receive correspondence mappings, reviewer notes,
 * source originals or audit metadata. It deliberately makes no source
 * layout/style/image/table/filename preservation claim.
 *
 * Documented round-trip normalization
 * -----------------------------------
 * The Safe string is split on CRLF, CR or LF into logical lines. Each logical
 * line becomes one OOXML paragraph (`<w:p>`); an empty logical line becomes an
 * empty paragraph (`<w:p/>`). Unicode is carried as UTF-8 and the XML text
 * metacharacters `& < > " '` are escaped. `mammoth.extractRawText()` emits,
 * for each paragraph, its text followed by exactly `"\n\n"`. The governed
 * inverse {@link normalizeDocxRawText} removes the final paragraph terminator
 * and rewrites every remaining `"\n\n"` separator as a single `"\n"`.
 * Consequence: CRLF/CR line endings normalize to LF on read-back; that is the
 * only declared normalization. Every other code point, leading/trailing
 * whitespace and XML metacharacter round-trips exactly.
 *
 * Fail-closed: XML 1.0 cannot carry NUL, most C0 control characters or
 * unpaired surrogates. Rather than emit a corrupt/invalid document, the
 * builder refuses explicitly with zero bytes produced.
 *
 * Privacy: memory-only local generation, no logging, no network, no
 * persistence, no third-party DOCX library.
 */
import JSZip from "jszip";

/** D-024 Safe DOCX download filename. */
export const SAFE_DOCX_FILENAME = "texto-preparado.docx";

/** Typed error for invalid/refused DOCX representation input. */
export class DocxBuildError extends Error {
  readonly code: string;
  constructor(code: string, message: string) {
    super(message);
    this.name = "DocxBuildError";
    this.code = code;
  }
}

/** mammoth's raw-text paragraph terminator (`raw-text.js`). */
const PARAGRAPH_TERMINATOR = "\n\n";

/** Fixed zip epoch keeps generated bytes deterministic and reproducible. */
const FIXED_ZIP_DATE = new Date(Date.UTC(1980, 0, 1, 0, 0, 0));

/**
 * One logical line as an OOXML paragraph. `xml:space="preserve"` keeps
 * leading/trailing spaces. Empty lines become empty paragraphs so blank-line
 * semantics survive the round trip.
 */
function paragraphXml(line: string): string {
  if (line === "") {
    return "<w:p/>";
  }
  return `<w:p><w:r><w:t xml:space="preserve">${escapeXmlText(line)}</w:t></w:r></w:p>`;
}

/** XML text-node escaping for the five XML metacharacters. */
function escapeXmlText(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/** XML 1.0 illegal characters: NUL/other C0 controls, unpaired surrogates, 0xFFFE/0xFFFF. */
const XML_ILLEGAL = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\uD800-\uDFFF\uFFFE\uFFFF]/u;

function assertXmlRepresentable(line: string): void {
  if (XML_ILLEGAL.test(line)) {
    throw new DocxBuildError(
      "XML_UNREPRESENTABLE_TEXT",
      "El texto contiene caracteres que XML no puede representar."
    );
  }
}

const CONTENT_TYPES_XML =
  `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n` +
  `<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">` +
  `<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>` +
  `<Default Extension="xml" ContentType="application/xml"/>` +
  `<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>` +
  `</Types>`;

const RELATIONSHIPS_XML =
  `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n` +
  `<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
  `<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>` +
  `</Relationships>`;

function buildDocumentXml(safeText: string): string {
  const lines = safeText.split(/\r\n|\r|\n/);
  for (const line of lines) {
    assertXmlRepresentable(line);
  }
  return (
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n` +
    `<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">` +
    `<w:body>${lines.map(paragraphXml).join("")}</w:body>` +
    `</w:document>`
  );
}

/**
 * Governed inverse of the DOCX text round trip (see the module header).
 * Throws when the raw text does not carry mammoth's paragraph terminator, so
 * a broken package can never be silently interpreted as valid output.
 */
export function normalizeDocxRawText(raw: string): string {
  if (!raw.endsWith(PARAGRAPH_TERMINATOR)) {
    throw new DocxBuildError(
      "INVALID_RAW_TEXT",
      "El texto extraído no termina en el separador de párrafo de mammoth."
    );
  }
  return raw.slice(0, -PARAGRAPH_TERMINATOR.length).split(PARAGRAPH_TERMINATOR).join("\n");
}

/**
 * Build the Safe DOCX artifact bytes from the canonical Safe string.
 * Resolves to the UTF-8 OOXML package; rejects with {@link DocxBuildError}
 * (zero bytes) when the content cannot be represented or the input is not a
 * string.
 */
export async function buildSafeDocxBytes(safeText: string): Promise<Uint8Array> {
  if (typeof safeText !== "string") {
    throw new DocxBuildError("INVALID_SAFE_TEXT", "El contenido DOCX debe ser una cadena.");
  }
  const documentXml = buildDocumentXml(safeText);
  const zip = new JSZip();
  const options = { date: FIXED_ZIP_DATE, createFolders: false };
  zip.file("[Content_Types].xml", CONTENT_TYPES_XML, options);
  zip.file("_rels/.rels", RELATIONSHIPS_XML, options);
  zip.file("word/document.xml", documentXml, options);
  return zip.generateAsync({
    type: "uint8array",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
    platform: "UNIX",
  });
}
