/**
 * Focused writer-phase oracle for the REC-07 #88 batch Safe deliverables
 * (`batchSafeDeliverables.ts`).
 *
 * Every test is capable of disagreeing with the implementation: content is
 * read back from the REAL generated bytes (ZIP entries via `jszip`,
 * PDF text via the legacy pdf.js read-back seam already used by
 * `pdf-builder.test.ts`), never from the derivation inputs.
 *
 * All fixtures are synthetic; no real content anywhere.
 */
import JSZip from "jszip";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import {
  BATCH_SAFE_CONSOLIDATED_PDF_FILENAME,
  BATCH_SAFE_ZIP_FILENAME,
  BatchSafeDeliverablesError,
  batchSafeDocumentEntryName,
  buildBatchConsolidatedPdfBytes,
  buildBatchSafeZipBytes,
  deriveBatchSafeDocuments,
} from "./batchSafeDeliverables";
import { serializeBatchSummaryCsv } from "./batchResultModel";
import {
  applyDecision,
  createReviewSession,
  getFinalText,
  type ReviewSession,
} from "../review/review-domain";
import {
  batchReviewComplete,
  beginItemProcessing,
  beginItemRead,
  createJob,
  recordItemProcessed,
  recordItemRead,
  recordItemReviewCompletion,
  removeBatchItem,
  withReviewState,
  type Job,
} from "../domain/job";
import { PdfRepresentationError } from "../output/pdf-builder";

// ---------------------------------------------------------------------------
// pdf.js read-back (same seam as pdf-builder.test.ts)
// ---------------------------------------------------------------------------

interface PdfTextItem {
  str: string;
}
interface PdfPage {
  getTextContent(): Promise<{ items: PdfTextItem[] }>;
}
interface PdfDocument {
  numPages: number;
  getPage(index: number): Promise<PdfPage>;
}
interface PdfJsApi {
  getDocument(params: { data: Uint8Array; isEvalSupported: boolean }): {
    promise: Promise<PdfDocument>;
  };
}

let pdfjs: PdfJsApi;

beforeAll(async () => {
  const [lib, worker] = await Promise.all([
    import("pdfjs-dist/legacy/build/pdf.js"),
    import("pdfjs-dist/legacy/build/pdf.worker.js"),
  ]);
  (globalThis as { pdfjsWorker?: unknown }).pdfjsWorker = worker;
  pdfjs = lib as unknown as PdfJsApi;
});

afterAll(() => {
  delete (globalThis as { pdfjsWorker?: unknown }).pdfjsWorker;
});

async function extractPdfText(bytes: Uint8Array): Promise<string> {
  const doc = await pdfjs.getDocument({ data: bytes, isEvalSupported: false }).promise;
  const pages: string[] = [];
  for (let index = 1; index <= doc.numPages; index++) {
    const page = await doc.getPage(index);
    const content = await page.getTextContent();
    pages.push(content.items.map((item) => item.str).join(" "));
  }
  return pages.join("\n");
}

async function extractPdfPages(bytes: Uint8Array): Promise<number> {
  const doc = await pdfjs.getDocument({ data: bytes, isEvalSupported: false }).promise;
  return doc.numPages;
}

const collapse = (value: string): string => value.replace(/\s+/g, " ").trim();

// ---------------------------------------------------------------------------
// Batch fixtures (same domain transitions as ExportStep.test.tsx)
// ---------------------------------------------------------------------------

function buildBatchJob(names: readonly string[]): Job {
  return createJob({
    type: "files",
    files: names.map((name) => ({ name, extension: "txt" })),
  });
}

function readOk(job: Job, index: number, text: string): Job {
  return recordItemRead(beginItemRead(job, index), index, { ok: true, extractedText: text });
}

function completeItem(job: Job, index: number, text: string): Job {
  const processed = recordItemProcessed(
    beginItemProcessing(readOk(job, index, text), index),
    index
  );
  return recordItemReviewCompletion(processed, index, true);
}

function derivedBatch(job: Job): Job {
  return withReviewState(job, { complete: batchReviewComplete(job) });
}

/** Finalizable session with NO detections: final text is the source text. */
function plainSession(text: string, id: string): ReviewSession {
  return createReviewSession({ originalText: text, detections: [], sessionId: id });
}

/** Finalizable session whose Safe text differs from the source (one accepted decision). */
function decidedSession(): { session: ReviewSession; safeText: string } {
  const source = "Paciente: Elena Ruiz. Teléfono 600111222.";
  const start = source.indexOf("Elena Ruiz");
  const session = createReviewSession({
    originalText: source,
    detections: [
      {
        type: "NOMBRE",
        start,
        end: start + "Elena Ruiz".length,
        confidence: 0.95,
        proposed: "PACIENTE-1",
        requiresReview: true,
      },
    ],
    sessionId: "decided-session",
  });
  const decided = applyDecision(session, session.detections[0].id, "accepted");
  return { session: decided, safeText: getFinalText(decided) };
}

// ---------------------------------------------------------------------------
// Adversarial sentinels: each lives in exactly one authority and must never
// reach a shareable Safe artifact.
// ---------------------------------------------------------------------------

const FILENAME_SENTINEL = "DNI-99999111-SENTINEL-informe.txt";
const ELIMINATED_CONTENT_SENTINEL = "DATO-ORIGEN-SENTINEL-ELIMINADO";
const REVIEWER_NOTE_SENTINEL = "NOTA-REVISION-SENTINEL-XYZ";
const CONFIDENTIAL_ORIGINAL_SENTINEL = "600999888";

function adversarialBatch(): { job: Job; sessions: Record<number, ReviewSession> } {
  // Item 0: source content that must NOT survive (replaced), a reviewer note
  // that must never appear in output, and Confidential-only original material.
  const source =
    `Informe sintético. ${ELIMINATED_CONTENT_SENTINEL} debe desaparecer. ` +
    `Teléfono ${CONFIDENTIAL_ORIGINAL_SENTINEL}.`;
  const eliminatedStart = source.indexOf(ELIMINATED_CONTENT_SENTINEL);
  const phoneStart = source.indexOf(CONFIDENTIAL_ORIGINAL_SENTINEL);
  const raw = createReviewSession({
    originalText: source,
    detections: [
      {
        type: "IDENTIFICADOR",
        start: eliminatedStart,
        end: eliminatedStart + ELIMINATED_CONTENT_SENTINEL.length,
        confidence: 0.9,
        proposed: "DATO-SUSTITUTO",
        note: REVIEWER_NOTE_SENTINEL,
        requiresReview: true,
      },
      {
        type: "IDENTIFICADOR",
        start: phoneStart,
        end: phoneStart + CONFIDENTIAL_ORIGINAL_SENTINEL.length,
        confidence: 0.9,
        proposed: "TEL-1",
        requiresReview: true,
      },
    ],
    sessionId: "adversarial-0",
  });
  let session0 = applyDecision(raw, raw.detections[0].id, "accepted");
  session0 = applyDecision(session0, raw.detections[1].id, "accepted");
  const session1 = plainSession("Segundo documento sintético sin marcas.", "adversarial-1");

  let job = buildBatchJob([FILENAME_SENTINEL, "informe-b.txt"]);
  job = completeItem(job, 0, source);
  job = completeItem(job, 1, "Segundo documento sintético sin marcas.");
  return { job: derivedBatch(job), sessions: { 0: session0, 1: session1 } };
}

describe("ordinal identity (closed decision: never the source filename)", () => {
  it("derives deterministic ordinal entry names from the stable batch index", () => {
    expect(batchSafeDocumentEntryName(1)).toBe("documento-seguro-01.pdf");
    expect(batchSafeDocumentEntryName(2)).toBe("documento-seguro-02.pdf");
    expect(batchSafeDocumentEntryName(12)).toBe("documento-seguro-12.pdf");
  });

  it("uses fixed Spanish artifact filenames", () => {
    expect(BATCH_SAFE_ZIP_FILENAME).toBe("lote-documentos-seguros.zip");
    expect(BATCH_SAFE_CONSOLIDATED_PDF_FILENAME).toBe("lote-seguro-consolidado.pdf");
  });
});

describe("canonical-material oracle: Safe content == getFinalText, never a rerun transform", () => {
  it("derives every included document from that item's final ReviewSession content", () => {
    const { session, safeText } = decidedSession();
    expect(safeText).not.toContain("Elena Ruiz");
    const other = plainSession("Texto llano sintético.", "oracle-plain");
    const base = buildBatchJob(["doc-a.txt", "doc-b.txt"]);
    let ready = completeItem(base, 0, "held source");
    ready = derivedBatch(completeItem(ready, 1, "held other"));
    const documents = deriveBatchSafeDocuments(ready, { 0: session, 1: other });
    expect(documents).toHaveLength(2);
    expect(documents[0].batchIndex).toBe(1);
    expect(documents[0].entryName).toBe("documento-seguro-01.pdf");
    expect(documents[0].safeText).toBe(safeText);
    expect(documents[0].safeText).toBe(getFinalText(session));
    expect(documents[1].safeText).toBe("Texto llano sintético.");
  });

  it("reads ZIP entry bytes back as the accepted Safe PDF of each final text", async () => {
    const { session, safeText } = decidedSession();
    const other = plainSession("Texto llano sintético.", "plain-1");
    const base = buildBatchJob(["doc-a.txt", "doc-b.txt"]);
    let job = completeItem(base, 0, "held A");
    job = completeItem(job, 1, "held B");
    const documents = deriveBatchSafeDocuments(derivedBatch(job), { 0: session, 1: other });

    const zipBytes = await buildBatchSafeZipBytes(documents);
    const zip = await JSZip.loadAsync(zipBytes);
    const names = Object.keys(zip.files).sort();
    expect(names).toEqual(["documento-seguro-01.pdf", "documento-seguro-02.pdf"]);
    for (const document of documents) {
      const entry = zip.files[document.entryName];
      expect(entry).toBeDefined();
      const bytes = await entry.async("uint8array");
      expect(collapse(await extractPdfText(bytes))).toBe(collapse(document.safeText));
    }
    expect(
      collapse(await extractPdfText(await zip.files["documento-seguro-01.pdf"].async("uint8array")))
    ).toBe(collapse(safeText));
  });
});

describe("no-leak adversary: sentinels stay out of every shareable Safe artifact", () => {
  it("keeps filename, eliminated content, reviewer note and Confidential-only material out of the ZIP", async () => {
    const { job, sessions } = adversarialBatch();
    const documents = deriveBatchSafeDocuments(job, sessions);
    expect(documents).toHaveLength(2);

    const zipBytes = await buildBatchSafeZipBytes(documents);
    const zip = await JSZip.loadAsync(zipBytes);
    const entryNames = Object.keys(zip.files);
    // Entry names carry ordinal identity only.
    expect(entryNames.sort()).toEqual(["documento-seguro-01.pdf", "documento-seguro-02.pdf"]);
    for (const name of entryNames) {
      expect(name).not.toContain(FILENAME_SENTINEL);
      expect(name).not.toContain("DNI-");
    }
    // Entry content carries only the prepared Safe text.
    for (const name of entryNames) {
      const text = await extractPdfText(await zip.files[name].async("uint8array"));
      expect(text).not.toContain(FILENAME_SENTINEL);
      expect(text).not.toContain(ELIMINATED_CONTENT_SENTINEL);
      expect(text).not.toContain(REVIEWER_NOTE_SENTINEL);
      expect(text).not.toContain(CONFIDENTIAL_ORIGINAL_SENTINEL);
    }
    // The Safe text itself proves the replaced content survived only as its substitute.
    expect(documents[0].safeText).toContain("DATO-SUSTITUTO");
    expect(documents[0].safeText).toContain("TEL-1");
  });

  it("keeps every sentinel out of the consolidated PDF and its index", async () => {
    const { job, sessions } = adversarialBatch();
    const documents = deriveBatchSafeDocuments(job, sessions);

    const bytes = await buildBatchConsolidatedPdfBytes(documents);
    const text = await extractPdfText(bytes);
    expect(text).toContain("Documento 1");
    expect(text).toContain("Documento 2");
    expect(text).toContain("DATO-SUSTITUTO");
    expect(text).not.toContain(FILENAME_SENTINEL);
    expect(text).not.toContain("DNI-99999111-SENTINEL");
    expect(text).not.toContain(ELIMINATED_CONTENT_SENTINEL);
    expect(text).not.toContain(REVIEWER_NOTE_SENTINEL);
    expect(text).not.toContain(CONFIDENTIAL_ORIGINAL_SENTINEL);
    // Index + covers + sections: strictly more pages than bare documents.
    expect(await extractPdfPages(bytes)).toBeGreaterThan(2);
  });
});

describe("manifest/disposition preservation: #87 CSV unchanged, removed items produce no body", () => {
  it("derives no document body for a removed error while the CSV keeps its error,retirado row", async () => {
    let job = buildBatchJob(["falla.txt", "ok.txt"]);
    job = recordItemRead(beginItemRead(job, 0), 0, {
      ok: false,
      error: { code: "pdf-no-text-layer", message: "El PDF no tiene capa de texto." },
    });
    job = completeItem(job, 1, "Contenido sintético B.");
    job = derivedBatch(removeBatchItem(job, 0));
    const sessions = { 1: plainSession("Contenido sintético B.", "removed-1") };

    // The #87 manifest is byte-unchanged: every original index, removed kept.
    expect(serializeBatchSummaryCsv(job)).toBe(
      ["indice_lote,estado,disposicion", "1,error,retirado", "2,completado,"].join("\n")
    );
    // The new deliverables hold exactly one body, addressed by original index.
    const documents = deriveBatchSafeDocuments(job, sessions);
    expect(documents).toHaveLength(1);
    expect(documents[0].batchIndex).toBe(2);
    expect(documents[0].entryName).toBe("documento-seguro-02.pdf");

    const zip = await JSZip.loadAsync(await buildBatchSafeZipBytes(documents));
    expect(Object.keys(zip.files)).toEqual(["documento-seguro-02.pdf"]);
    const consolidatedText = await extractPdfText(await buildBatchConsolidatedPdfBytes(documents));
    expect(consolidatedText).toContain("Documento 2");
    expect(consolidatedText).not.toContain("Documento 1 —");
  });

  it("cover keeps the stable original-index ordinal without the included-count denominator", async () => {
    // A lower original index is absent (removed), so the single included
    // document is original index 2 while the included count is 1. The cover
    // must not present that included count as the denominator of the
    // original-index ordinal (the old "Documento 2 de 1" false denominator).
    let job = buildBatchJob(["falla.txt", "ok.txt"]);
    job = recordItemRead(beginItemRead(job, 0), 0, {
      ok: false,
      error: { code: "pdf-no-text-layer", message: "El PDF no tiene capa de texto." },
    });
    job = completeItem(job, 1, "Contenido sintético B.");
    job = derivedBatch(removeBatchItem(job, 0));
    const documents = deriveBatchSafeDocuments(job, {
      1: plainSession("Contenido sintético B.", "cover-ordinal-1"),
    });
    expect(documents).toHaveLength(1);
    expect(documents[0].batchIndex).toBe(2);

    const text = collapse(await extractPdfText(await buildBatchConsolidatedPdfBytes(documents)));
    expect(text).toContain("Documento 2");
    expect(text).not.toContain("Documento 2 de 1");
  });
});

describe("all-or-nothing representation refusal (planted PDF-unrepresentable character)", () => {
  function unrepresentableBatch(): { job: Job; sessions: Record<number, ReviewSession> } {
    let job = buildBatchJob(["ok.txt", "griego.txt"]);
    job = completeItem(job, 0, "Contenido sintético A.");
    job = completeItem(job, 1, "Dosis de prueba con alfa.");
    const ready = derivedBatch(job);
    return {
      job: ready,
      sessions: {
        0: plainSession("Contenido sintético A.", "allornothing-0"),
        // α (U+03B1) is outside the REC-05 WinAnsi frontier: the final text
        // is otherwise ready, so only the representation refuses.
        1: plainSession("Dosis de prueba α 10 mg.", "allornothing-1"),
      },
    };
  }

  it("derivation is representation-independent but each build refuses with zero bytes", async () => {
    const { job, sessions } = unrepresentableBatch();
    // Readiness is representation-independent: derivation still succeeds.
    const documents = deriveBatchSafeDocuments(job, sessions);
    expect(documents).toHaveLength(2);
    // Each affected batch artifact action refuses truthfully with ZERO bytes
    // (the rejection carries no bytes at all, never a partial artifact).
    await expect(buildBatchSafeZipBytes(documents)).rejects.toBeInstanceOf(PdfRepresentationError);
    await expect(buildBatchConsolidatedPdfBytes(documents)).rejects.toBeInstanceOf(
      PdfRepresentationError
    );
  });
});

describe("fail-closed authorization (reuses batchSafeSummaryReady, invents no second truth)", () => {
  function readyTwo(): { job: Job; sessions: Record<number, ReviewSession> } {
    let job = buildBatchJob(["a.txt", "b.txt"]);
    job = completeItem(job, 0, "Contenido sintético A.");
    job = completeItem(job, 1, "Contenido sintético B.");
    return {
      job: derivedBatch(job),
      sessions: {
        0: plainSession("Contenido sintético A.", "auth-0"),
        1: plainSession("Contenido sintético B.", "auth-1"),
      },
    };
  }

  it("refuses a needs-attention batch, a blocked batch and a missing session set", () => {
    const { job, sessions } = readyTwo();
    // Missing session authority.
    expect(() => deriveBatchSafeDocuments(job, null)).toThrow(BatchSafeDeliverablesError);
    // Completeness mismatch (same CORA-87-01 shape as the CSV guard).
    const mismatched = withReviewState(job, { complete: false });
    expect(() => deriveBatchSafeDocuments(mismatched, sessions)).toThrow(
      BatchSafeDeliverablesError
    );
    // Active failure blocks.
    let blockedJob = buildBatchJob(["x.txt", "y.txt"]);
    blockedJob = recordItemRead(beginItemRead(blockedJob, 0), 0, {
      ok: false,
      error: { code: "pdf-no-text-layer", message: "El PDF no tiene capa de texto." },
    });
    blockedJob = completeItem(blockedJob, 1, "Contenido sintético B.");
    blockedJob = derivedBatch(blockedJob);
    expect(() => deriveBatchSafeDocuments(blockedJob, sessions)).toThrow(
      BatchSafeDeliverablesError
    );
    // A completed row without its session refuses rather than fabricating.
    expect(() => deriveBatchSafeDocuments(job, { 0: sessions[0] })).toThrow(
      BatchSafeDeliverablesError
    );
  });

  it("refuses to build from an empty derivation", async () => {
    await expect(buildBatchSafeZipBytes([])).rejects.toBeInstanceOf(BatchSafeDeliverablesError);
    await expect(buildBatchConsolidatedPdfBytes([])).rejects.toBeInstanceOf(
      BatchSafeDeliverablesError
    );
  });
});
